# deploy
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-spring-petclinic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-petclinic
  template:
    metadata:
      labels:
        app: spring-petclinic
    spec:
      containers:
      - name: my-spring
        image: kaksacr12345.azurecr.io/bprasanna881/spring-petclinc:#{Build.BuildId}#
        imagePullPolicy: Always
        ports:
        - containerPort: 8085
## test2
##2
---
# https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service
kind: Service
apiVersion: v1
metadata:
  name: spring-petclinic-service
spec:
  selector:
    app: spring-petclinic
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8085
  type: LoadBalancer
