# deploy
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-springboot-petclinicdeployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springboot-app-petclinic
  template:
    metadata:
      labels:
        app: springboot-app-petclinic
    spec:
      containers:
      - name: my-springboot-app
        image: kaksacr12345.azurecr.io/bprasanna881/aks-spring-classic:#{Build.BuildId}#
        imagePullPolicy: Always
        ports:
        - containerPort: 8085
        resources:
          limits:
            cpu: 300m
          requests:
            cpu: 100m
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: springboot-app-petclinic
    k8s-app: springboot-app-petclinic
  name: springboot-app-petclinic
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8085
  type: LoadBalancer
  selector:
    app: springboot-app-petclinic
  
